# Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
- reality-blue-jekyll-theme.gemspec
- .jekyll-cache

# SASS Configuration
sass:
    sass_dir: _sass

# Plugins and plugin settings
plugins:
- jekyll-paginate
paginate: 5

# Site Settings
title: Terry Wen