# Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
- reality-blue-jekyll-theme.gemspec
- .jekyll-cache

# SASS Configuration
sass:
    sass_dir: _sass

# Plugins and plugin settings
plugins:
- jekyll-paginate
- jekyll-remote-theme
paginate: 5

# Theme
remote_theme: terry-wen/reality-blue@0.1.3

# Site Settings
title: terry wen
author: Terry Wen
sections:
    - name:
      file: about.html
    - name: about
      file: about.html
    - name:
      file: about.html
icons:
    - name: about
      perRow: 3
      size: 72
    - name: projects
      perRow: 3
      size: 96
    - name: social
      perRow: 4
      size: 48